
#define DEBUG_OS
#define LOG_OS


#define			ERR_INVALID_PROCESS_NAME				22L
#define			ERR_INVALID_PROCESS_PRIORITY			23L
#define			ERR_DUPLICATE_PROCESS_NAME				24L
#define			ERR_INVALID_PROCESS_ID					25L
#define			ERR_MAX_NUM_EXCEEDED					26L
#define			ERR_UNAUTHORIZED_TERMINATION			27L
#define			ERR_BUFFER_LENGTH_EXCEEDED				28L
#define 		ERR_INVALID_STATE_TRANSITION			29L
